name: business_card_app
description: A new Flutter project.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/dp2.png
    - images/dp1.png

  fonts:
    - family: Chewy
      fonts:
        - asset: fonts/Chewy-Regular.ttf

    - family: Corben
      fonts:
        - asset: fonts/Corben-Bold.ttf

    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf